// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DoughnutFactory.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.4.20220.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DoughnutFactory.Entities.DoughnutTreeNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("NegativeNodeId")
                        .HasColumnType("int");

                    b.Property<int?>("PositiveNodeId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NegativeNodeId");

                    b.HasIndex("PositiveNodeId");

                    b.ToTable("DoughnutTreeNodes");
                });

            modelBuilder.Entity("DoughnutFactory.Entities.DoughnutTreeNode", b =>
                {
                    b.HasOne("DoughnutFactory.Entities.DoughnutTreeNode", "NegativeNode")
                        .WithMany()
                        .HasForeignKey("NegativeNodeId");

                    b.HasOne("DoughnutFactory.Entities.DoughnutTreeNode", "PositiveNode")
                        .WithMany()
                        .HasForeignKey("PositiveNodeId");
                });
#pragma warning restore 612, 618
        }
    }
}
